/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.acira.vista;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

/**
 *
 * @author wilme
 */
@ViewScoped
@ManagedBean(name = "MbTerminosAcira")
public class MbTerminosAcira implements Serializable {

    private String contenido;

    public MbTerminosAcira() {
    }

    @PostConstruct
    public void init() {
        contenido = "<font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p align=\"center\" style=\"background: white; margin: 22.5pt 0cm; text-align: center; line-height: normal; mso-outline-level: 2;\"><b style=\"mso-bidi-font-weight: normal;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Arial\",sans-serif; font-size: 13.5pt; mso-fareast-font-family: \"Times New Roman\"; mso-themecolor: accent2; mso-fareast-language: ES-CO;'>REGLAMENTO DE USO DEL PORTAL\n"
                + "MÓVIL (PERSONAS NATURALES Y PERSONAS JURÍDICAS)</span></b></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>El presente documento\n"
                + "establece las condiciones mediante las cuales se regirá el uso de la aplicación\n"
                + "móvil: <b style=\"mso-bidi-font-weight: normal;\">ACIRA SECURITY</b> Colombia (en\n"
                + "adelante la aplicación), la cual es operada por&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>LEAF COMPANY S.A.S</span></strong>,\n"
                + "compañía constituida en Colombia y domiciliada en la ciudad de Santa Marta.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>La aplicación funcionará\n"
                + "como un nuevo sistema de seguridad inteligente con el objeto de proporcionar\n"
                + "una herramienta tecnológica a los ciudadanos para mitigar las posibles\n"
                + "situaciones delictivas.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>El usuario se compromete a\n"
                + "leer los términos y condiciones aquí establecidas, previamente a la descarga de\n"
                + "la aplicación, por tanto, en caso de realizar la instalación se entiende que\n"
                + "cuenta con el conocimiento integral de este documento y la consecuente\n"
                + "aceptación de la totalidad de sus estipulaciones.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>El Usuario reconoce que el\n"
                + "ingreso de su información personal, y los datos que contiene la aplicación a su\n"
                + "disposición, la realizan de manera voluntaria, quienes optan por acceder a esta\n"
                + "aplicación en Colombia o desde fuera del territorio nacional, lo hacen por\n"
                + "iniciativa propia y son responsables del cumplimiento de las leyes locales, en\n"
                + "la medida en que dichas leyes sean aplicables en su correspondiente país. En\n"
                + "caso de que se acceda por parte de menores de edad, deben contar con la\n"
                + "supervisión de un adulto en todo momento desde la descarga y durante el uso de\n"
                + "la aplicación, en el evento en que no se cumpla esta condición, le agradecemos\n"
                + "no hacer uso de esta tecnología.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 22.5pt 0cm; line-height: normal; mso-outline-level: 2;\"><b style=\"mso-bidi-font-weight: normal;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-fareast-font-family: \"Times New Roman\"; mso-themecolor: accent2; mso-fareast-language: ES-CO; mso-bidi-font-family: \"Times New Roman\";'>ALCANCE Y USO</span></b></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt; mso-fareast-font-family: \"Times New Roman\"; mso-fareast-language: ES-CO;'>El usuario de la aplicación entiende y acepta que no obstante es operada\n"
                + "por&nbsp;<b>LEAF COMPANY S.A.S</b>,<b style=\"mso-bidi-font-weight: normal;\">ACIRA\n"
                + "SECURITY</b> no se hace responsable de cualquier situación delictiva en la que\n"
                + "se vea expuesto cualquiera de sus usuarios<b style=\"mso-bidi-font-weight: normal;\">,\n"
                + "ACIRA SECURITY</b> se crea con la finalidad de brindarle a cada individuo una\n"
                + "herramienta para prevenir <span style=\"mso-spacerun: yes;\">&nbsp;</span>y accionar\n"
                + "eventos delictivos, partiendo de la base de cuidarnos unos a los otros a través\n"
                + "de esta tecnología, por ende no garantiza el no afrontar cualquiera de esas\n"
                + "situaciones mencionadas anteriormente.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>REQUISITOS PARA USO</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>El usuario deberá contar\n"
                + "con un dispositivo móvil inteligente (Smartphone) o Tableta con sistema\n"
                + "operativo Android, cualquiera de estos con acceso a internet, ambos seguros y\n"
                + "confiables. <b style=\"mso-bidi-font-weight: normal;\">ACIRA SECURITY</b> no será\n"
                + "responsable por la seguridad de los equipos Smartphone propiedad de los\n"
                + "usuarios utilizados para el acceso al canal, ni por la disponibilidad del\n"
                + "servicio en los dispositivos en los cuales se descargue la aplicación.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>En la forma permitida por\n"
                + "la ley, los materiales de la aplicación se suministran sin garantía de ningún\n"
                + "género, expresa o implícita, incluyendo sin limitación las garantías de calidad\n"
                + "satisfactoria, comerciabilidad, adecuación para un fin particular o no\n"
                + "infracción, por tanto,&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA\n"
                + "SECURITY</span></strong> no garantiza el funcionamiento adecuado en los\n"
                + "distintos sistemas operativos o dispositivos en los cuales se haga uso de la\n"
                + "aplicación.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Para acceder al portal, <b style=\"mso-bidi-font-weight: normal;\">EL USUARIO</b> contará con Usuario y Clave,\n"
                + "que lo identifica en su relación con&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA SECURITY</span></strong>, sólo cuando el cliente\n"
                + "ingrese desde un equipo registrado y siempre y cuando no cierre la sección no\n"
                + "se solicitará responder las preguntas definidas con anterioridad.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>OBLIGACIONES DE LOS USUARIOS</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"margin: 0cm 0cm 8pt;\"><span style='background: white; color: rgb(51, 51, 51); line-height: 107%; font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>El Usuario se obliga a usar\n"
                + "la aplicación y los contenidos encontrados en ella de una manera diligente,\n"
                + "correcta, lícita y en especial, se compromete a NO realizar las conductas descritas\n"
                + "a continuación:</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><ul style=\"list-style-type: disc; direction: ltr;\"><li style=\"color: rgb(51, 51, 51); font-style: normal; font-weight: normal;\"><p style=\"background: white; color: rgb(0, 0, 0); line-height: normal; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 11.25pt; mso-margin-top-alt: auto; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;\"><span style='color: rgb(51, 51, 51); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>(a) Utilizar los contenidos de forma, con fines o efectos\n"
                + "contrarios a la ley, a la moral y a las buenas costumbres generalmente\n"
                + "aceptadas o al orden público;</span></p></li><li style='color: rgb(51, 51, 51); font-family: \"Times New Roman\",serif; font-size: 12pt; font-style: normal; font-weight: normal;'><p style='background: white; color: rgb(0, 0, 0); line-height: normal; font-family: \"Calibri\",sans-serif; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 11.25pt; mso-margin-top-alt: auto; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;'><span style='color: rgb(51, 51, 51); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>(b) Reproducir, copiar, representar, utilizar, distribuir,\n"
                + "transformar o modificar los contenidos de la aplicación, por cualquier\n"
                + "procedimiento o sobre cualquier soporte, total o parcial, o permitir el acceso\n"
                + "del público a través de cualquier modalidad de comunicación pública;</span></p></li><li style='color: rgb(51, 51, 51); font-family: \"Times New Roman\",serif; font-size: 12pt; font-style: normal; font-weight: normal;'><p style='background: white; color: rgb(0, 0, 0); line-height: normal; font-family: \"Calibri\",sans-serif; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 11.25pt; mso-margin-top-alt: auto; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;'><span style='color: rgb(51, 51, 51); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>(c) Utilizar los contenidos de cualquier manera que entrañen un\n"
                + "riesgo de daño o inutilización de la aplicación o de los contenidos o de\n"
                + "terceros; es decir que ninguno de sus usuarios puede utilizar su condigo\n"
                + "personal para hacer bromas o saboteos frente a sus funciones de pánico y\n"
                + "sospecha.</span></p></li><li style='color: rgb(51, 51, 51); font-family: \"Times New Roman\",serif; font-size: 12pt; font-style: normal; font-weight: normal;'><p style='background: white; color: rgb(0, 0, 0); line-height: normal; font-family: \"Calibri\",sans-serif; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 11.25pt; mso-margin-top-alt: auto; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;'><span style='color: rgb(51, 51, 51); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>(d) Suprimir, eludir o manipular el derecho de autor y demás\n"
                + "datos identificativos de los derechos de autor incorporados a los contenidos,\n"
                + "así como los dispositivos técnicos de protección, o cualesquiera mecanismos de\n"
                + "información que pudieren tener los contenidos;</span></p></li><li style='color: rgb(51, 51, 51); font-family: \"Times New Roman\",serif; font-size: 12pt; font-style: normal; font-weight: normal;'><p style='background: white; color: rgb(0, 0, 0); line-height: normal; font-family: \"Calibri\",sans-serif; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 11.25pt; mso-margin-top-alt: auto; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;'><span style='color: rgb(51, 51, 51); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>(e) Emplear los contenidos y, en particular, la información de\n"
                + "cualquier clase obtenida a través de la aplicación para distribuir, transmitir,\n"
                + "remitir, modificar, rehusar o reportar la publicidad o los contenidos de esta\n"
                + "con fines de venta directa o con cualquier otra clase de finalidad comercial,\n"
                + "mensajes no solicitados dirigidos a una pluralidad de personas con\n"
                + "independencia de su finalidad, así como comercializar o divulgar de cualquier\n"
                + "modo dicha información;</span></p></li><li style='color: rgb(51, 51, 51); font-family: \"Times New Roman\",serif; font-size: 12pt; font-style: normal; font-weight: normal;'><p style='background: white; color: rgb(0, 0, 0); line-height: normal; font-family: \"Calibri\",sans-serif; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 11.25pt; mso-margin-top-alt: auto; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;'><span style='color: rgb(51, 51, 51); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>(f) No permitir que terceros ajenos a usted usen la aplicación\n"
                + "móvil con su clave;</span></p></li><li style='color: rgb(51, 51, 51); font-family: \"Times New Roman\",serif; font-size: 12pt; font-style: normal; font-weight: normal;'><p style='background: white; color: rgb(0, 0, 0); line-height: normal; font-family: \"Calibri\",sans-serif; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 11.25pt; mso-margin-top-alt: auto; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;'><span style='color: rgb(51, 51, 51); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>g) Utilizar la aplicación y los contenidos con fines lícitos y/o\n"
                + "ilícitos, contrarios a lo establecido en estos Términos y Condiciones, o al uso\n"
                + "mismo de la aplicación, que sean lesivos de los derechos e intereses de terceros,\n"
                + "o que de cualquier forma puedan dañar, inutilizar, sobrecargar o deteriorar la\n"
                + "aplicación y los contenidos o impedir la normal utilización o disfrute de esta\n"
                + "y de los contenidos por parte de los usuarios.<span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>&nbsp;</span></span></p></li></ul><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>PROPIEDAD INTELECTUAL</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Todo el material informático,\n"
                + "gráfico, publicitario, fotográfico, de multimedia, audiovisual y de diseño, así\n"
                + "como todos los contenidos, textos y bases de datos puestos a su disposición en\n"
                + "esta aplicación están protegidos por derechos de autor y/o propiedad industrial\n"
                + "cuyo titular es<span style=\"mso-spacerun: yes;\">&nbsp; </span>LEAF COMPANY S.A.S, o su\n"
                + "creador Jesús David Callejas Cabarcas y cofundador Wilmer Quintero en algunos\n"
                + "casos, de terceros que han autorizado su uso o explotación. Igualmente, el uso\n"
                + "en la aplicación de algunos materiales de propiedad de terceros se encuentra\n"
                + "expresamente autorizado por la ley o por dichos terceros. Todos los contenidos\n"
                + "en la aplicación están protegidos por las normas sobre derecho de autor y por\n"
                + "todas las normas nacionales e internacionales que le sean aplicables.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Exceptuando lo\n"
                + "expresamente estipulado en estos Términos y Condiciones, queda prohibido todo\n"
                + "acto de copia, reproducción, modificación, creación de trabajos derivados,\n"
                + "venta o distribución, exhibición de los contenidos de esta aplicación, de\n"
                + "manera o por medio alguno, incluyendo, más no limitado a, medios electrónicos,\n"
                + "mecánicos, de fotocopiado, de grabación o de cualquier otra índole, sin el\n"
                + "permiso previo y por escrito de ACIRA SECURITY o del titular de los respectivos\n"
                + "derechos.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>En ningún caso estos Términos y Condiciones\n"
                + "confieren derechos, licencias ni autorizaciones para realizar los actos\n"
                + "anteriormente prohibidos. Cualquier uso no autorizado de los contenidos\n"
                + "constituirá una violación del presente documento y a las normas vigentes sobre\n"
                + "derechos de autor, a las normas vigentes nacionales e internacionales sobre Propiedad\n"
                + "Industrial, y a cualquier otra que sea aplicable.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>LICENCIA PARA COPIAR PARA USO PERSONAL</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Ninguna parte de la\n"
                + "aplicación podrá ser reproducida o transmitida o almacenada en otro sitio web o\n"
                + "en otra forma de sistema de recuperación electrónico.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Ya sea que se reconozca\n"
                + "específicamente o no, las marcas comerciales, las marcas de servicio y los\n"
                + "logos visualizados en esta aplicación pertenecen a <b style=\"mso-bidi-font-weight: normal;\">LEAF COMPANY S.A.S</b>, sus socios promocionales u otros terceros.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>INTEGRACIÓN CON OTRAS APLICACIONES</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Los links de Facebook®,\n"
                + "Instagram®, twitter®, Youtube en esta aplicación pueden mostrar contenido que\n"
                + "no están bajo el control de&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA\n"
                + "SECURITY.</span></strong></span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Aunque esta aplicación\n"
                + "de&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>LEAF COMPANY S.A.S</span></strong>&nbsp;trata\n"
                + "de suministrar links solamente a sitios y aplicaciones de terceros que cumplan\n"
                + "con las leyes y regulaciones aplicables y las normas de&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA SECURITY</span></strong>, el\n"
                + "Usuario debe entender que&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA\n"
                + "SECURITY</span></strong>&nbsp;no tiene control sobre la naturaleza y el\n"
                + "contenido de esos sitios y no está recomendando estos sitios, la información\n"
                + "que contienen ni los productos o servicios de terceros.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>ACIRA\n"
                + "SECURITY</span></strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>&nbsp;no acepta responsabilidad por el contenido del sitio de un\n"
                + "tercero con el cual existe un link de hipertexto y no ofrece garantía\n"
                + "(explícita o implícita) en cuanto al contenido de la información en esos\n"
                + "sitios, ya que no recomienda estos sitios.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Usted debe verificar las\n"
                + "secciones de términos y condiciones, política legal y de privacidad de algunos\n"
                + "otros sitios de ACIRA SECURITY&nbsp;o de un tercero con los cuales se enlaza.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>ACIRA\n"
                + "SECURITY </span></strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>no asume ninguna responsabilidad por pérdida directa, indirecta\n"
                + "o consecuencial por el uso de un sitio de un tercero.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>USO DE INFORMACIÓN Y PRIVACIDAD</span></h2><font face=\"Times New Roman\" size=\"3\"><strong>\n"
                + "\n"
                + "</strong></font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Con la\n"
                + "descarga de la APP usted acepta y autoriza que LEAF COMPANY S.A.S, utilice sus\n"
                + "datos en calidad de responsable del tratamiento para fines derivados de la\n"
                + "ejecución de la APP. LEAF COMPANY S.A.S informa que podrá ejercer sus derechos\n"
                + "a conocer, actualizar, rectificar y suprimir su información personal; así como\n"
                + "el derecho a revocar el consentimiento otorgado para el tratamiento de datos\n"
                + "personales previstos en la ley 1581 de 2012, observando nuestra política de\n"
                + "tratamiento de información del teléfono 3205500492, siendo voluntario responder\n"
                + "preguntas sobre información sensible o de menores de edad.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>LEAF\n"
                + "COMPANY S.A.S. podrá dar a conocer, transferir y/o trasmitir sus datos\n"
                + "personales dentro y fuera del país a cualquier empresa miembro del grupo LEAF\n"
                + "COMPANY S.A.S, así como a terceros a consecuencia de un contrato, ley o vínculo\n"
                + "lícito que así lo requiera, para todo lo anterior otorgo mi autorización\n"
                + "expresa e inequívoca.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>De\n"
                + "conformidad a lo anterior autoriza el tratamiento de su información en los\n"
                + "términos señalados, y transfiere a&nbsp;<strong>ACIRA SECURITY&nbsp;</strong>de manera total, y\n"
                + "sin limitación mis derechos de imagen y patrimoniales de autor, de manera\n"
                + "voluntaria, previa, explicita, informada e inequívoca.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>RESPONSABILIDAD DE ACIRA SECURITY.</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>ACIRA\n"
                + "SECURITY</span></strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>&nbsp;procurará garantizar disponibilidad, continuidad o buen\n"
                + "funcionamiento de la aplicación. ACIRA SECURITY<strong><span style='font-family: \"Arial\",sans-serif;'>&nbsp;podrá bloquear, interrumpir o restringir el acceso a\n"
                + "esta cuando lo considere necesario para el mejoramiento de la aplicaci</span></strong>ón\n"
                + "o por dada de baja de la misma.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Se recomienda al Usuario\n"
                + "tomar medidas adecuadas y actuar diligentemente al momento de acceder a la\n"
                + "aplicación, como por ejemplo, contar con programas de protección, antivirus,\n"
                + "para manejo de malware, spyware y herramientas similares.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>ACIRA\n"
                + "SECURITY</span></strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>&nbsp;no será responsable por: a) Fuerza mayor o caso fortuito;\n"
                + "b) Por la pérdida, extravío o hurto de su dispositivo móvil que implique el\n"
                + "acceso de terceros a la aplicación móvil; c) Por errores en la digitación o\n"
                + "accesos por parte del cliente; d) Por los perjuicios, lucro cesante, daño\n"
                + "emergente, morales, y en general sumas a cargo de&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA SECURITY</span></strong>, por los\n"
                + "retrasos, no procesamiento de información o suspensión del servicio del\n"
                + "operador móvil o daños en los dispositivos móviles.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><b style=\"mso-bidi-font-weight: normal;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt; mso-fareast-font-family: \"Times New Roman\"; mso-fareast-language: ES-CO;'>ACIRA SECURITY</span></b><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt; mso-fareast-font-family: \"Times New Roman\"; mso-fareast-language: ES-CO;'> no se hace\n"
                + "responsable de cualquier situación delictiva en la que se vea expuesto\n"
                + "cualquiera de sus usuarios<b style=\"mso-bidi-font-weight: normal;\">, ACIRA\n"
                + "SECURITY</b> se crea con la finalidad de prevenir acciones delictivas,\n"
                + "partiendo de la base de cuidarnos unos a los otros a través de esta herramienta\n"
                + "la cual no lo exime de afrontar cualquiera de esas situaciones mencionadas\n"
                + "anteriormente.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm; vertical-align: top;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2; mso-bidi-font-family: Arial;'>DENEGACIÓN Y RETIRADA DEL ACCESO A LA APLICACIÓN</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; line-height: 13.5pt; vertical-align: top;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>En el Evento en que un\n"
                + "Usuario incumpla estos Términos y Condiciones, o cualesquiera otras\n"
                + "disposiciones que resulten de aplicación,&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA SECURITY</span></strong>&nbsp;podrá suspender su\n"
                + "acceso a la aplicación.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm; vertical-align: top;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2; mso-bidi-font-family: Arial;'>TÉRMINOS Y CONDICIONES</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt; vertical-align: top;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>El\n"
                + "Usuario acepta expresamente los Términos y Condiciones, siendo condición\n"
                + "esencial para la utilización de la aplicación. En el evento en que se encuentre\n"
                + "en desacuerdo con estos Términos y Condiciones, solicitamos abandonar la\n"
                + "aplicación inmediatamente.&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA\n"
                + "SECURITY</span></strong>&nbsp;podrá modificar los presentes términos y\n"
                + "condiciones, avisando a los usuarios de la aplicación mediante publicación En\n"
                + "los perfiles de sus redes sociales&nbsp;o mediante la difusión de las\n"
                + "modificaciones por algún medio electrónico, redes sociales, SMS y/o correo\n"
                + "electrónico, lo cual se entenderá aceptado por el usuario si éste continua con\n"
                + "el uso de la aplicación.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>JURISDICCIÓN</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Estos términos y condiciones y todo lo que\n"
                + "tenga que ver con esta aplicación, se rigen por las leyes de colombianas.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>USO DE INFORMACIÓN NO PERSONAL</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>ACIRA\n"
                + "SECURITY</span></strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>&nbsp;también recolecta información no personal en forma\n"
                + "agregada para seguimiento de datos como el número total de descargas de la\n"
                + "aplicación. Utilizamos esta información, que permanece en forma agregada, para\n"
                + "entender el comportamiento de la aplicación.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><h2 style=\"background: white; margin: 22.5pt 0cm;\"><span style='color: rgb(237, 125, 49); text-transform: uppercase; letter-spacing: -0.75pt; font-family: \"Gill Sans W01\",serif; font-size: 13.5pt; mso-bidi-font-weight: normal; mso-themecolor: accent2;'>SEGURIDAD</span></h2><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>ACIRA\n"
                + "SECURITY</span></strong><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>&nbsp;está comprometido en la protección de la seguridad de su\n"
                + "información personal.&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA\n"
                + "SECURITY</span></strong>&nbsp;tiene implementados mecanismos de seguridad que\n"
                + "aseguran la protección de la información personal, así como los accesos\n"
                + "únicamente al personal y sistemas autorizados, también contra la pérdida, uso\n"
                + "indebido y alteración de sus datos de usuario bajo nuestro control.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><p style=\"background: white; margin: 0cm 0cm 7.5pt; text-align: justify; line-height: 13.5pt;\"><span style='color: rgb(50, 50, 50); font-family: \"Arial\",sans-serif; font-size: 10.5pt;'>Excepto como se indica a\n"
                + "continuación, sólo personal autorizado tiene acceso a la información que nos\n"
                + "proporciona. Además, hemos impuesto reglas estrictas a los empleados de&nbsp;<strong><span style='font-family: \"Arial\",sans-serif;'>ACIRA SECURITY</span></strong>&nbsp;con\n"
                + "acceso a las bases de datos que almacenan información del usuario o a los\n"
                + "servidores que hospedan nuestros servicios.</span></p><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font><font face=\"Times New Roman\" size=\"3\">\n"
                + "\n"
                + "</font>";
    }

    public String getContenido() {
        return contenido;
    }

    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

}
